task: реализовал detail-page
js-tasks-ru/htmlcss-20220519_ruslan-aliev-n pull request #12
Opened 2022-06-03 12:11 UTC by rkaliev

task: реализовал detail-page

2022-06-03 12:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-05 10:55 UTC, GSemikozov requested changes

2022-06-05 10:55 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__title_page-detail {
уже есть модификатор для всего блока, дублировать для каждого дочернего элемента не надо, можно так: `.footer_page-detail .footer__title {}`

2022-06-05 10:55 UTC, GSemikozov commented on components/main/main.css
> +.main__inner_page-detail {
`.main_page-detail .main__inner {}`

2022-06-05 11:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-05 18:28 UTC, GSemikozov approved these changes

2022-06-05 18:28 UTC, merged