task: реализовал button
js-tasks-ru/htmlcss-20220519_ruslan-aliev-n pull request #3
Opened 2022-05-24 11:01 UTC by rkaliev

task: реализовал button

2022-05-24 11:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-24 18:54 UTC, GSemikozov requested changes

2022-05-24 18:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    --btn-primary-color: var(--white);
таким образом оформленные переменные на самом деле не переиспользуются, а используются лишь раз, а значит - в них нет смысла, значения можно проставлять сразу на месте) 
`background-color: var(--blue-2);` и тд

2022-05-24 18:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 182px;
ширину можно жестко не фиксировать, самый простой кейс когда это сломается - это если добавить длинный текст

2022-05-24 18:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    pointer-events: none;
pointer-events: none; и так по умолчанию делает курсор default )

2022-05-24 19:43 UTC, rkaliev commented on 03-lection1/01-button/button.css
> +    pointer-events: none;
Спасибо, поправил

2022-05-24 19:44 UTC, rkaliev commented on 03-lection1/01-button/button.css
> +    width: 182px;
Убрал жесткую ширину, щас кнопки шириной по контенту

2022-05-24 19:47 UTC, rkaliev commented on 03-lection1/01-button/button.css
> +    --btn-primary-color: var(--white);
Идея была в том, чтоб иметь в компоненте кнопки набор свойств отвечающих за основную стилизацию, поэтому и добавил префикс --btn, если с этим префиксом вынести в main.css тоже смыла не будет, так как вряд ли свойства --btn могут понадобиться где то еще, а так попросят сменить какие-то цвета, идем в кнопку тут и меняем. Поправил на переменные из main.css. Спасибо!

2022-05-25 08:51 UTC, GSemikozov approved these changes

2022-05-25 08:51 UTC, merged